name: Scrape IMDb Top 250

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install httpx lxml cssselect

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push changes
        run: |
          git config --local user.email "21f2000296@ds.study.iitm.ac.in"
          git config --local user.name "adityasuraj-iitm"
          git add *.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update IMDb Top 250 data [skip ci]"
          git push
