name: Daily Commit Workflow

on:
  schedule:
    # Runs daily at 02:30 UTC (change the time as needed)
    - cron: "30 2 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Commit by 21f2000296@ds.study.iitm.ac.in"
        run: echo "Running daily commit workflow"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make a Change
        run: |
          echo "Workflow ran at $(date)" > run-log.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "21f2000296@ds.study.iitm.ac.in"
          git config --local user.name "adityasuraj-iitm"
          git add run-log.txt
          git commit -m "Daily commit: $(date --utc +'%Y-%m-%d %H:%M:%S UTC')"
          git push
